spring.application.name=hms-backend

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/hsmdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Ri$petto12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=hms-super-secret-key-change-this-in-production-must-be-at-least-256-bits
jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:4200
